import * as T from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { paints, type Settings,type PartGroup,type View } from './experience';
export type Hotspot={id:string;x:number;y:number;visible:boolean};
export type Viewer={apply:(s:Settings)=>void;dispose:()=>void;zoom:(factor:number)=>void;capture:()=>string;quality:(high:boolean)=>void};
type Piece={mesh:T.Mesh;base:T.Matrix4;center:T.Vector3;offset:T.Vector3;group:PartGroup;door:string|null;materials:T.MeshStandardMaterial[];variant?:string};
const cameras:Record<View,{position:number[];target:number[]}>={hero:{position:[-6.9,3.0,-8.3],target:[0,.85,0]},front:{position:[0,1.65,-9],target:[0,.9,0]},side:{position:[-9,1.8,0],target:[0,.8,0]},rear:{position:[5.8,2.6,7.8],target:[0,.85,0]},driver:{position:[-.42,1.38,-.12],target:[-.4,1.28,-2.1]},second:{position:[.18,1.43,1.1],target:[.15,1.2,-1.8]},third:{position:[.05,1.39,1.96],target:[.08,1.2,-.7]}};
const doors=['Door_LF','Door_RF','Door_LB','Door_RB','Trunk_up','Hood'];
function ancestry(o:T.Object3D){const names=[];while(o){names.push(o.name);if(!o.parent)break;o=o.parent;}return names.join('/');}
export async function createViewer(host:HTMLElement,initial:Settings,onProgress:(n:number)=>void,onHotspots:(h:Hotspot[])=>void,onPick:(id:string)=>void,onCount:(n:number)=>void,onTimeline:(p:number)=>void):Promise<Viewer>{
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;host.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive ZEEKR 9X 3D scene');
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(38,1,.025,160);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=3.2;controls.maxDistance=21;controls.maxPolarAngle=Math.PI*.49;controls.autoRotateSpeed=.5;controls.enablePan=false;
 const environment=new RoomEnvironment();const pmrem=new T.PMREMGenerator(renderer);const env=pmrem.fromScene(environment,.04);scene.environment=env.texture;environment.dispose();pmrem.dispose();
 const hemi=new T.HemisphereLight(0xe7efff,0x5a4c43,2.0);scene.add(hemi);const key=new T.DirectionalLight(0xffe7d1,4.5);key.position.set(-3,7,-5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-7;key.shadow.camera.right=7;key.shadow.camera.top=7;key.shadow.camera.bottom=-7;key.shadow.normalBias=.035;key.shadow.bias=-.0003;scene.add(key);const rim=new T.DirectionalLight(0xc8defc,2.7);rim.position.set(5,4,4);scene.add(rim);
 const floorMat=new T.MeshStandardMaterial({color:0xc9c5be,roughness:.65,metalness:.1});const floor=new T.Mesh(new T.PlaneGeometry(180,180),floorMat);floor.rotation.x=-Math.PI/2;floor.position.y=-.018;floor.receiveShadow=true;scene.add(floor);
 const ring=new T.Mesh(new T.RingGeometry(4.12,4.135,160),new T.MeshBasicMaterial({color:0x8d8579,transparent:true,opacity:.35,side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.002;scene.add(ring);
 let settings=initial,disposed=false,lastView='',tween=1,interior=false,frame=0,lastTime=performance.now(),progress=initial.progress,frameCount=0;const pieces:Piece[]=[],doorPivots:Record<string,T.Vector3>={},fromPos=new T.Vector3(),fromTarget=new T.Vector3(),toPos=new T.Vector3(),toTarget=new T.Vector3();
 const gltf=await new GLTFLoader().loadAsync('/models/zeekr-9x.glb',e=>onProgress(e.total?Math.round(100*e.loaded/e.total):0));const car=gltf.scene;scene.add(car);car.updateMatrixWorld(true);
 const wheelCenters:T.Vector3[]=[];car.traverse(o=>{if(o.name.startsWith('Tire_dabing'))wheelCenters.push(new T.Box3().setFromObject(o).getCenter(new T.Vector3()));});
 doors.forEach(name=>{const o=car.getObjectByName(name);if(o)doorPivots[name]=o.getWorldPosition(new T.Vector3());});
 const variant=await new GLTFLoader().loadAsync('/models/seat-layout-a.glb');scene.add(variant.scene);variant.scene.updateMatrixWorld(true);const meshes:T.Mesh[]=[];variant.scene.traverse(o=>{if((o as T.Mesh).isMesh)meshes.push(o as T.Mesh);});car.traverse(o=>{if((o as T.Mesh).isMesh)meshes.push(o as T.Mesh);});
 const leatherCanvas=document.createElement('canvas');leatherCanvas.width=256;leatherCanvas.height=256;const lctx=leatherCanvas.getContext('2d')!;const data=lctx.createImageData(256,256);let seed=173;for(let i=0;i<data.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;let v=116+(seed%35);data.data.set([v,v,v,255],i);}lctx.putImageData(data,0,0);const grain=new T.CanvasTexture(leatherCanvas);grain.wrapS=grain.wrapT=T.RepeatWrapping;grain.repeat.set(70,70);
 for(const mesh of meshes){const path=ancestry(mesh);const mats=(Array.isArray(mesh.material)?mesh.material:[mesh.material]).map(m=>m.clone() as T.MeshStandardMaterial);mesh.material=mats.length===1?mats[0]:mats;const materialNames=mats.map(m=>m.name).join(' ');const door=doors.find(d=>path.split('/').includes(d))??null;let group:PartGroup=door?'doors':/9X_INT|Car_INT|Carbody_INT|Seat_Layout_A/.test(path)?'cabin':/Tire_|Rims_|Calipers|brake_disc/.test(path)?'wheels':/lamp|DLP|DRL|Light_|Light_logo/.test(path)?'lights':/Glass/.test(materialNames)&&mats.every(m=>m.name.startsWith('Glass'))?'glass':'body';
  for(const mat of mats){mat.userData={baseOpacity:mat.opacity,baseTransparent:mat.transparent,baseEmissive:mat.emissive?.clone()??new T.Color(0),baseColor:mat.color.clone()};if(mat.name.startsWith('car_paint')){mat.roughness=.21;mat.metalness=.72;mat.envMapIntensity=1.5;}if(/Chrome|Molding|lungujinshu|Grille/.test(mat.name)){mat.roughness=.2;mat.metalness=.95;mat.envMapIntensity=1.2;}if(mat.name.startsWith('Glass')){mat.transparent=true;mat.opacity=/Black/.test(mat.name)?.42:.22;mat.depthWrite=false;mat.roughness=.07;mat.envMapIntensity=1.8;mat.side=T.DoubleSide;mat.userData.baseOpacity=mat.opacity;mat.userData.baseTransparent=true;}if(mat.name.startsWith('INT')){mat.userData.tint={value:new T.Color(1,1,1)};mat.userData.tintMix={value:0};mat.onBeforeCompile=shader=>{shader.uniforms.cabinTint=mat.userData.tint;shader.uniforms.cabinTintMix=mat.userData.tintMix;shader.fragmentShader='uniform vec3 cabinTint; uniform float cabinTintMix;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>', '#include <map_fragment>\nfloat leatherLuma=dot(diffuseColor.rgb,vec3(0.2126,0.7152,0.0722));\ndiffuseColor.rgb=mix(diffuseColor.rgb,vec3(leatherLuma)*cabinTint,cabinTintMix);');};mat.customProgramCacheKey=()=> 'leather-tint-v1';mat.roughness=.74;mat.metalness=0;mat.bumpMap=grain;mat.bumpScale=.003;mat.envMapIntensity=.45;}if(/luntai|Rubber/.test(mat.name)){mat.roughness=.87;mat.metalness=0;}if(mat.emissive)mat.emissiveIntensity=0;}
  const center=new T.Box3().setFromObject(mesh).getCenter(new T.Vector3());const offset=center.clone().sub(new T.Vector3(0,.6,0));if(offset.length()<.1)offset.set(0,1,0);offset.normalize().multiplyScalar(group==='lights'?.9:1.35);if(group==='cabin')offset.y+=.7;if(group==='glass')offset.y+=.65;
  scene.attach(mesh);mesh.castShadow=group!=='glass';mesh.receiveShadow=true;mesh.matrixAutoUpdate=false;pieces.push({mesh,base:mesh.matrix.clone(),center,offset,group,door,materials:mats,variant:path.includes('Seat_Layout_A')?'seatA':path.includes('Carbody_INT_seat_B')?'seatB':(/lunguhei|lungujinshu/.test(materialNames)?'originalRim':undefined)});mesh.userData.group=group;mesh.userData.door=door;
 }
 scene.remove(car);scene.remove(variant.scene);
 const customRims=new T.Group();const rimMaterials:T.MeshStandardMaterial[]=[];
 wheelCenters.forEach(center=>{const g=new T.Group();const sign=Math.sign(center.x);g.position.copy(center);g.position.x+=sign*.129;const mat=new T.MeshStandardMaterial({color:0x9da8af,metalness:.95,roughness:.23});mat.userData={baseOpacity:1,baseTransparent:false};rimMaterials.push(mat);const lip=new T.Mesh(new T.TorusGeometry(.279,.019,10,56),mat);lip.rotation.y=Math.PI/2;g.add(lip);const hub=new T.Mesh(new T.CylinderGeometry(.065,.065,.06,32),mat);hub.rotation.z=Math.PI/2;g.add(hub);for(let i=0;i<10;i++){const spoke=new T.Mesh(new T.BoxGeometry(.025,.22,.035),mat);const a=i*Math.PI/5;spoke.position.set(0,Math.cos(a)*.16,Math.sin(a)*.16);spoke.rotation.x=a;spoke.userData.spoke=i;g.add(spoke);}scene.add(g);g.updateMatrixWorld(true);const originalChildren=[...g.children] as T.Mesh[];for(const mesh of originalChildren){scene.attach(mesh);mesh.matrixAutoUpdate=false;mesh.castShadow=true;pieces.push({mesh,base:mesh.matrix.clone(),center:center.clone(),offset:new T.Vector3(sign*1.7,.25,center.z*.18),group:'wheels',door:null,materials:[mat],variant:'customRim'});}scene.remove(g);});
 const tireCanvas=document.createElement('canvas');tireCanvas.width=256;tireCanvas.height=256;const tc=tireCanvas.getContext('2d')!;tc.fillStyle='#999';tc.fillRect(0,0,256,256);tc.strokeStyle='#333';tc.lineWidth=4;for(let y=0;y<256;y+=20){tc.beginPath();tc.moveTo(0,y);tc.lineTo(128,y+18);tc.lineTo(256,y);tc.stroke();}const tread=new T.CanvasTexture(tireCanvas);tread.wrapS=tread.wrapT=T.RepeatWrapping;tread.repeat.set(4,4);onCount(pieces.filter(p=>p.variant!=='customRim'&&p.variant!=='seatA').length);
 const hudCanvas=document.createElement('canvas');hudCanvas.width=768;hudCanvas.height=384;const hc=hudCanvas.getContext('2d')!;hc.clearRect(0,0,768,384);hc.fillStyle='#b4fff1';hc.font='500 100px sans-serif';hc.fillText('48',65,155);hc.font='24px sans-serif';hc.fillText('km/h',75,190);hc.font='70px sans-serif';hc.fillText('↱',320,150);hc.font='30px sans-serif';hc.fillText('300 m',435,135);hc.strokeStyle='#b4fff1';hc.lineWidth=5;hc.beginPath();hc.moveTo(260,310);hc.lineTo(335,210);hc.moveTo(530,310);hc.lineTo(455,210);hc.stroke();hc.font='18px sans-serif';hc.fillText('HUD / CONCEPT',75,345);
 const hudTexture=new T.CanvasTexture(hudCanvas);const hud=new T.Mesh(new T.PlaneGeometry(.64,.32),new T.MeshBasicMaterial({map:hudTexture,transparent:true,opacity:.82,depthWrite:false,side:T.DoubleSide,toneMapped:false}));hud.position.set(-.42,1.28,-1.37);hud.rotation.x=-.14;scene.add(hud);
 const ambientMat=new T.MeshBasicMaterial({color:initial.ambient,toneMapped:false});const ambient=new T.Group();const curve=new T.CatmullRomCurve3([new T.Vector3(-.74,1.02,-.92),new T.Vector3(-.4,1.06,-1.02),new T.Vector3(.35,1.06,-1.02),new T.Vector3(.75,1.02,-.92)]);ambient.add(new T.Mesh(new T.TubeGeometry(curve,44,.0035,5,false),ambientMat));scene.add(ambient);const cabinLight=new T.PointLight(initial.ambient,.6,3,2);cabinLight.position.set(0,1.5,.1);scene.add(cabinLight);
 const beam=new T.Group();for(const x of [-.7,.7]){const light=new T.SpotLight(0xe4f0ff,0,13,.43,.65,1.1);light.position.set(x,.65,-2.35);light.target.position.set(x,.02,-10);beam.add(light,light.target);}scene.add(beam);
 const road=new T.Group();for(const x of [-1.9,1.9]){for(let z=-18;z<20;z+=3){const line=new T.Mesh(new T.PlaneGeometry(.055,1.4),new T.MeshBasicMaterial({color:0xe2dace}));line.rotation.x=-Math.PI/2;line.position.set(x,.003,z);road.add(line);}}scene.add(road);
 const sensors=new T.Group();function fan(x:number,z:number,rotation:number,radius:number,angle:number){const g=new T.Group();for(let i=1;i<=3;i++){const arc=new T.Mesh(new T.RingGeometry(radius*i/3-.013,radius*i/3+.013,70,1,-angle/2,angle),new T.MeshBasicMaterial({color:0x68cdbb,transparent:true,opacity:.55,side:T.DoubleSide,depthWrite:false}));arc.rotation.x=-Math.PI/2;arc.rotation.z=rotation;g.add(arc);}const fill=new T.Mesh(new T.CircleGeometry(radius,70,-angle/2,angle),new T.MeshBasicMaterial({color:0x68cdbb,transparent:true,opacity:.055,side:T.DoubleSide,depthWrite:false}));fill.rotation.x=-Math.PI/2;fill.rotation.z=rotation;g.add(fill);g.position.set(x,.035,z);sensors.add(g);return g;}const frontFan=fan(0,-2.3,Math.PI/2,6,Math.PI*.55);const sideFan=fan(-.9,.7,Math.PI,4.5,Math.PI*.6);const backFan=fan(0,2.3,-Math.PI/2,3.4,Math.PI*.75);scene.add(sensors);
 const actors=new T.Group();const actorMat=new T.MeshStandardMaterial({color:0x709eaf,roughness:.45,metalness:.25});const other=new T.Group();const otherBody=new T.Mesh(new T.BoxGeometry(1.45,.5,3),actorMat);otherBody.position.y=.55;other.add(otherBody);const otherTop=new T.Mesh(new T.BoxGeometry(1.2,.45,1.45),new T.MeshStandardMaterial({color:0x253c48,roughness:.3}));otherTop.position.set(0,1,-.05);other.add(otherTop);for(const x of [-.72,.72])for(const z of [-1,1]){const wheel=new T.Mesh(new T.CylinderGeometry(.28,.28,.13,20),new T.MeshStandardMaterial({color:0x161a1c,roughness:.8}));wheel.rotation.z=Math.PI/2;wheel.position.set(x,.28,z);other.add(wheel);}actors.add(other);
 const pedestrian=new T.Group();const torso=new T.Mesh(new T.CapsuleGeometry(.19,.55,5,10),new T.MeshStandardMaterial({color:0xc4a37e}));torso.position.y=1;pedestrian.add(torso);const head=new T.Mesh(new T.SphereGeometry(.16,14,10),new T.MeshStandardMaterial({color:0xe1c5a2}));head.position.y=1.6;pedestrian.add(head);for(const x of [-.12,.12]){const leg=new T.Mesh(new T.CapsuleGeometry(.07,.5,4,8),new T.MeshStandardMaterial({color:0x3a4149}));leg.position.set(x,.38,0);pedestrian.add(leg);}actors.add(pedestrian);
 const cycle=new T.Group();for(const z of [-.52,.52]){const wheel=new T.Mesh(new T.TorusGeometry(.31,.035,7,24),new T.MeshStandardMaterial({color:0x333a40}));wheel.rotation.y=Math.PI/2;wheel.position.set(0,.33,z);cycle.add(wheel);}const frameGeo=new T.BufferGeometry().setFromPoints([new T.Vector3(0,.33,-.52),new T.Vector3(0,.8,0),new T.Vector3(0,.33,.52),new T.Vector3(0,.33,-.52)]);cycle.add(new T.Line(frameGeo,new T.LineBasicMaterial({color:0xe2b37e})));const rider=pedestrian.clone();rider.position.y=.35;cycle.add(rider);actors.add(cycle);scene.add(actors);
 const ringRisk=new T.Mesh(new T.RingGeometry(.7,.735,70),new T.MeshBasicMaterial({color:0xffa64d,transparent:true,opacity:.85,side:T.DoubleSide}));ringRisk.rotation.x=-Math.PI/2;ringRisk.position.y=.045;scene.add(ringRisk);
 const anchorList=[{id:'Door_LF',p:new T.Vector3(-1.05,1.05,-.55),inside:false},{id:'Door_RF',p:new T.Vector3(1.05,1.05,-.55),inside:false},{id:'lights',p:new T.Vector3(-.72,.9,-2.3),inside:false},{id:'driver',p:new T.Vector3(-.4,1.65,-.1),inside:false},{id:'screen',p:new T.Vector3(.2,1.06,-1.05),inside:true},{id:'seat',p:new T.Vector3(.45,.85,.65),inside:true},{id:'ambient',p:new T.Vector3(.65,1.07,-.86),inside:true}];
 const raycaster=new T.Raycaster();let pointerStart={x:0,y:0};function down(e:PointerEvent){pointerStart={x:e.clientX,y:e.clientY};if(interior){const dir=new T.Vector3();camera.getWorldDirection(dir);lookYaw=Math.atan2(dir.x,-dir.z);lookPitch=Math.asin(dir.y);}}let lookYaw=0,lookPitch=0;
 function move(e:PointerEvent){if(!interior||!e.buttons)return;lookYaw-=(e.clientX-pointerStart.x)*.004;lookPitch=T.MathUtils.clamp(lookPitch+(e.clientY-pointerStart.y)*.003,-1.15,1.15);pointerStart={x:e.clientX,y:e.clientY};const d=new T.Vector3(Math.sin(lookYaw)*Math.cos(lookPitch),Math.sin(lookPitch),-Math.cos(lookYaw)*Math.cos(lookPitch));camera.lookAt(camera.position.clone().add(d));}
 let pressStart={x:0,y:0};const clickDown=(e:PointerEvent)=>{pressStart={x:e.clientX,y:e.clientY};down(e);renderer.domElement.setPointerCapture(e.pointerId);};function up(e:PointerEvent){if(Math.hypot(e.clientX-pressStart.x,e.clientY-pressStart.y)>5||interior)return;const rect=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=raycaster.intersectObjects(pieces.filter(p=>p.mesh.visible).map(p=>p.mesh),false)[0];if(hit)onPick(settings.section==='structure'?hit.object.userData.group:hit.object.userData.door??hit.object.userData.group);}
 renderer.domElement.addEventListener('pointerdown',clickDown);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);
 function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}const ro=new ResizeObserver(resize);ro.observe(host);resize();
 function apply(s:Settings){if(s.progress!==settings.progress)progress=s.progress;const sceneChanged=s.mode!==settings.mode;const materialsChanged=!frame||['paint','transparent','hidden','isolated','selected','section','wheelStyle','tireStyle','seatStyle','backrest'].some(k=>(s as unknown as Record<string,unknown>)[k]!==(settings as unknown as Record<string,unknown>)[k]);settings=s;const cv=s.section==='safety'?'safety':s.view;if(lastView!==cv){lastView=cv;interior=['driver','second','third'].includes(s.view)&&s.section!=='safety';fromPos.copy(camera.position);fromTarget.copy(controls.target);const c=s.section==='safety'?{position:[-9,9,-12],target:[0,.2,0]}:cameras[s.view];toPos.fromArray(c.position);toTarget.fromArray(c.target);if(!frame){fromPos.copy(toPos);fromTarget.copy(toTarget);}tween=0;camera.fov=interior?78:38;camera.updateProjectionMatrix();controls.enabled=!interior;}
  controls.autoRotate=s.orbit&&!interior&&s.section!=='safety';const night=s.mode==='night',day=s.mode==='day';scene.background=new T.Color(night?0x101721:day?0xd5dfdf:0xd8d4cc);floorMat.color.set(night?0x1d2731:day?0xbdc9c4:0xc8c3bb);hemi.intensity=night?.55:day?3.2:1.7;key.intensity=night?.9:day?4.5:3.3;rim.intensity=night?2.7:2.3;renderer.toneMappingExposure=night?1.05:1.25;scene.environmentIntensity=night?.38:1.05;ambientMat.color.set(s.ambient);cabinLight.color.set(s.ambient);cabinLight.intensity=interior?.8:.12;hud.visible=s.hud&&interior;ambient.visible=interior;road.visible=s.section==='safety';actors.visible=s.section==='safety';ring.visible=s.section!=='safety'&&!interior;beam.children.forEach(o=>{if((o as T.SpotLight).isSpotLight)(o as T.SpotLight).intensity=s.lights&&night?16:0;});
  if(materialsChanged)for(const p of pieces){p.mesh.visible=!s.hidden.includes(p.group)&&(!s.isolated||p.group===s.selected)&&(p.variant!=='seatA'||s.backrest==='A')&&(p.variant!=='seatB'||s.backrest==='B')&&(p.variant!=='originalRim'||s.wheelStyle==='mirror')&&(p.variant!=='customRim'||s.wheelStyle!=='mirror');for(const m of p.materials){if(m.userData.tint){m.userData.tint.value.set(s.seatStyle==='cognac'?'#b67f54':s.seatStyle==='ivory'?'#ffebce':'#ffffff');m.userData.tintMix.value=s.seatStyle==='blue'?0:1;}if(m.name==='luntai'){m.bumpMap=s.tireStyle==='touring'?tread:null;m.bumpScale=.009;m.roughness=s.tireStyle==='touring'?.92:.82;}if(p.variant==='customRim'){m.color.set(s.wheelStyle==='turbine'?0x73868e:0xb5b7b9);const index=p.mesh.userData.spoke;if(index!==undefined){const scale=s.wheelStyle==='turbine'?1.9:1;p.base.decompose(p.mesh.position,p.mesh.quaternion,p.mesh.scale);p.mesh.scale.z=scale;p.base.compose(p.mesh.position,p.mesh.quaternion,p.mesh.scale);}}if(m.name.startsWith('car_paint'))m.color.set(paints.find(p=>p.id===s.paint)?.hex??paints[0].hex);const xray=s.transparent&&['body','doors','glass'].includes(p.group);m.opacity=xray?.13:m.userData.baseOpacity;m.transparent=xray||m.userData.baseTransparent;m.depthWrite=!xray&&!m.name.startsWith('Glass');if(m.emissive){m.emissive.set(0);m.emissiveIntensity=0;if(s.section==='structure'&&p.group===s.selected){m.emissive.set(0xac743c);m.emissiveIntensity=.14;}}m.needsUpdate=true;}}
  if(sceneChanged)renderer.shadowMap.needsUpdate=true;
 }
 const translation=new T.Matrix4(),rotation=new T.Matrix4(),back=new T.Matrix4(),delta=new T.Matrix4();const doorAmounts:Record<string,number>={};let explosion=0;
 function animate(now:number){if(disposed)return;frame=requestAnimationFrame(animate);const dt=Math.min(.05,(now-lastTime)/1000);lastTime=now;if(document.hidden)return;const ease=1-Math.exp(-dt*7);if(tween<1){tween=Math.min(1,tween+dt*1.2);const t=tween*tween*(3-2*tween);camera.position.lerpVectors(fromPos,toPos,t);controls.target.lerpVectors(fromTarget,toTarget,t);camera.lookAt(controls.target);}else if(!interior)controls.update();
  explosion=T.MathUtils.lerp(explosion,settings.section==='structure'?settings.explode/100:0,ease);doors.forEach(d=>{doorAmounts[d]=T.MathUtils.lerp(doorAmounts[d]??0,settings.doors.includes(d)?1:0,ease);});
  const blink=Math.floor(now/450)%2===0;for(const p of pieces){p.mesh.matrix.copy(p.base);if(p.door&&doorPivots[p.door]&&doorAmounts[p.door]>.0001){const pivot=doorPivots[p.door],amount=doorAmounts[p.door];if(p.door==='Trunk_up')rotation.makeRotationX(-amount*1.05);else if(p.door==='Hood')rotation.makeRotationX(amount*.64);else rotation.makeRotationY(amount*(p.door.includes('_L')?-1:1)*1.06);translation.makeTranslation(pivot.x,pivot.y,pivot.z);back.makeTranslation(-pivot.x,-pivot.y,-pivot.z);delta.copy(translation).multiply(rotation).multiply(back);p.mesh.matrix.premultiply(delta);}p.mesh.matrix.elements[12]+=p.offset.x*explosion;p.mesh.matrix.elements[13]+=p.offset.y*explosion;p.mesh.matrix.elements[14]+=p.offset.z*explosion;p.mesh.matrixWorldNeedsUpdate=true;
   for(const m of p.materials){if(/lamp_|Light_LOGO|TopLight|starlit/.test(m.name)){m.emissive.set(/lamp_B|TopLight|Trunk/.test(m.name)?0xff1f0d:0xd4edff);m.emissiveIntensity=settings.lights?2.8:0;}if(/Mirro_Turn/.test(m.name)){m.emissive.set(0xff9a23);m.emissiveIntensity=settings.hazards&&blink?4:0;}if(m.name==='screen'){m.emissiveMap=m.map;m.emissive.set(0xffffff);m.emissiveIntensity=interior?.7:.18;}}
  }
  if(settings.section==='safety'){if(settings.playing&&progress<1){progress=Math.min(1,progress+dt/14);if(frameCount%6===0||progress===1)onTimeline(progress);}const risk=progress>.28&&progress<.8;const fault=settings.scenario==='sensor'&&progress>.28;sensors.visible=settings.radar&&!fault;frontFan.visible=settings.scenario==='parking'||settings.scenario==='sensor';sideFan.visible=settings.scenario==='blindspot'||settings.scenario==='door';backFan.visible=settings.scenario==='parking';sensors.traverse(o=>{if((o as T.Mesh).isMesh)((o as T.Mesh).material as T.MeshBasicMaterial).color.set(risk?0xf2a45b:0x68cdbb);});other.visible=settings.scenario==='blindspot';other.position.set(-3.25,0,8-progress*15);pedestrian.visible=settings.scenario==='parking';pedestrian.position.set(4-progress*8,0,-4.2);cycle.visible=settings.scenario==='door';cycle.position.set(-1.65,0,6-progress*13);ringRisk.visible=risk&&!fault;const actor=settings.scenario==='parking'?pedestrian:settings.scenario==='door'?cycle:other;ringRisk.position.set(actor.position.x,.045,actor.position.z);ringRisk.scale.setScalar(1+Math.sin(now*.004)*.1);}else{sensors.visible=false;ringRisk.visible=false;}
  renderer.render(scene,camera);if(frameCount++%5===0){const rect=host.getBoundingClientRect();const out=anchorList.map(a=>{const p=a.p.clone().project(camera);const delta=a.p.clone().sub(camera.position);const nearSide=interior||!(a.id==='Door_LF'&&camera.position.x>0||a.id==='Door_RF'&&camera.position.x<0||a.id==='lights'&&camera.position.z>0);const visible=nearSide&&settings.hotspots&&a.inside===interior&&settings.section!=='structure'&&settings.section!=='safety'&&p.z<1&&p.z>-1&&Math.abs(p.x)<.94&&Math.abs(p.y)<.85&&delta.dot(camera.getWorldDirection(new T.Vector3()))>0;return{id:a.id,x:(p.x*.5+.5)*rect.width,y:(-.5*p.y+.5)*rect.height,visible};});onHotspots(out);}
 }
 apply(initial);frame=requestAnimationFrame(animate);
 return{apply,zoom(factor){if(interior){camera.fov=T.MathUtils.clamp(camera.fov*factor,48,94);camera.updateProjectionMatrix();}else{camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);}},capture(){renderer.render(scene,camera);return renderer.domElement.toDataURL('image/png');},quality(high){renderer.setPixelRatio(Math.min(devicePixelRatio,high?2:1));resize();},dispose(){disposed=true;cancelAnimationFrame(frame);ro.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',clickDown);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);scene.traverse(o=>{const m=o as T.Mesh;if(m.geometry)m.geometry.dispose();if(m.material)for(const mat of Array.isArray(m.material)?m.material:[m.material])mat.dispose();});env.dispose();grain.dispose();tread.dispose();hudTexture.dispose();renderer.dispose();renderer.domElement.remove();}};
}
